# ===========================================================================
# Project:   Raclette
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore
proxy "/rails", :to => "localhost:3001"